/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*; //Consultas SQL
import clases.Conexion; //Para conexion que creamos
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter; //Eventos dentro la tabla
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 *
 * @author Christian
 */
public class GestionarUsuarios extends javax.swing.JFrame {

    String user;
    public static String user_update = "";
    DefaultTableModel model = new DefaultTableModel();  //Acceso a los métodos para modifica filas y/o columnas en la tabla

    public GestionarUsuarios() {
        initComponents();
        user = Login.user;
        this.setTitle("Usuarios registrados - Sesión de " + user + " -");
        this.setSize(630, 350);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);//Cerrar ventana sin acabar todo el proceso

        /// IMAGEN DE FONDO
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");   //Poner imagen de fondo
        //Adaptar el tamaño del JLabel LA IMAGEN Y ASÍ, con anchura, altura y que se escalable
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icono);   //Colocamos el objeto en el label
        this.repaint(); //Necesario por que a veces no se ve la imagen.

        //
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(""
                    + "select id_usuario,nombre_usuario,username,tipo_nivel,estatus from usuarios");
            ResultSet rs = pst.executeQuery();
            tab_usuarios = new JTable(model);
            scrollp_tabla.setViewportView(tab_usuarios); //Meter JTable en JScrollPane
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("UserName");
            model.addColumn("Permisos");
            model.addColumn("Estatus");
            while (rs.next()) { //Si la base encontró resultados
                Object[] fila = new Object[5]; //Necesita un vector la tabla, de tipo Object para llenar la tabla
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1); //Indice en 1 en rs
                }
                model.addRow(fila); //Agregamos fila después de llenar todas las columnas
            }
            cn.close(); //Cerramos la conexión

        } catch (SQLException e) {
            System.err.println("Error al llenar la tabla " + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar información, llame al Administrador");
        }
        
        //Evento para que se despliegue la información del usuario
        tab_usuarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) { //Sobreescribimos el método
                int fila_point = tab_usuarios.rowAtPoint(e.getPoint());//Obtener fila seleccionada o clickeada mediante un entero
                int columna_point = 2; //Para la segunda columna clickeada
                if (fila_point > -1 ) {  //No hay filas menores a 0
                    user_update = (String)model.getValueAt(fila_point, columna_point).toString();
                    InformacionUsuario info_usu = new InformacionUsuario(); //Abrir una nueva interfaz, la ventan InformacionUsuario
                    info_usu.setVisible(true);
                    System.out.println("Valor de userUpdate " + user_update);
                    
                }
            }
        });

    }

    //Icono de la ventana
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollp_tabla = new javax.swing.JScrollPane();
        tab_usuarios = new javax.swing.JTable();
        lbl_footer = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuarios Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        tab_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollp_tabla.setViewportView(tab_usuarios);

        getContentPane().add(scrollp_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 630, 180));

        lbl_footer.setText("Creado por Christian Elier De la Paz Barajas ©");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JScrollPane scrollp_tabla;
    private javax.swing.JTable tab_usuarios;
    // End of variables declaration//GEN-END:variables
}
