/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;   //Para poner imagenes

import java.sql.*;          //Para usar SQL
import clases.Conexion; //Para usar la clase que creamos para conectar
import java.awt.Color;
/**
 *
 * @author Christian
 */
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public static String user = "";     //Pasar variables entre interfaces
    String pass = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(400, 570);                         //Rectificamos las medidas del Login
        this.setResizable(false);                    //Sin que se pueda deformar el tamaño
        this.setTitle("Acceso al Sistema");   //Titulo interfaz
        this.setLocationRelativeTo(null);     //Al centro de la pantalla

        /// IMAGEN DE FONDO para LOGIN
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");   //Poner imagen de fondo
        //Adaptar el tamaño del JLabel LA IMAGEN Y ASÍ, con anchura, altura y que se escalable
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(), lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icono);   //Colocamos el objeto en el label
        this.repaint(); //Necesario por que a veces no se ve la imagen. 

        // IMAGEN LOGO
        ImageIcon wallpaper_logo = new ImageIcon("src/images/DS.png");              //Anchura                  //Altura                    //Escala   
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), Image.SCALE_DEFAULT));
        lbl_logo.setIcon(icono_logo);
        this.repaint();

    }

    //Para el ICONO DE LA INTERFAZ
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logo = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_acceder = new javax.swing.JButton();
        lbl_footer = new javax.swing.JLabel();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 270, 270));

        txt_user.setBackground(new java.awt.Color(153, 153, 255));
        txt_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, 210, -1));

        txt_password.setBackground(new java.awt.Color(153, 153, 255));
        txt_password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 370, 210, -1));

        btn_acceder.setBackground(new java.awt.Color(153, 153, 255));
        btn_acceder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn_acceder.setForeground(new java.awt.Color(255, 255, 255));
        btn_acceder.setText("Acceder");
        btn_acceder.setBorder(null);
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });
        getContentPane().add(btn_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 420, 210, 35));

        lbl_footer.setText("Creado por Christian Elier De la Paz Barajas ©");
        getContentPane().add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, 20));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed

        user = txt_user.getText().trim(); //Recogemos los datos de los textField
        pass = txt_password.getText().trim();

        if (!user.equals("") || !pass.equals("")) { //Si el usuario y la contrasea no sson diferentes de vació, es decir estan llenos
            try {
                Connection cn = Conexion.conectar();   //Instanciamos la clase Conexion con el metodo conectar para que se conete
                //CUIDADO CON LAS COMILLAS EN LAS CONSULTAS
                PreparedStatement pst = cn.prepareStatement(
                        "select tipo_nivel, estatus from usuarios where username= '" + user
                        + "' and password = '" + pass + "'");
                ResultSet rs = pst.executeQuery();    //Ejecutar Consulta
                //Validar si los datos son correctos
                if (rs.next()) {    //Cuando la consulta se realizó correctamente

                    String tipo_nivel = rs.getString("tipo_nivel"); //Jala datos de BD y guardamos en variable
                    String estatus = rs.getString("estatus");//Jala datos de BD y guardamos en variable

                    //VENTANA DE ADMINISTRADOR
                    if (tipo_nivel.equals("Administrador") && estatus.equalsIgnoreCase("Activo")) {  //IgnoreCase usado para no importar mayusculas
                        dispose();  //CERRAR VENTANA ACTIVA es decir el Login
                        new Administrador().setVisible(true); //Abrimos ventana Administrador

                        //VENTANA DE TÉCNICO
                    } else if (tipo_nivel.equals("Tecnico") && estatus.equalsIgnoreCase("Activo")) {
                        dispose();  //CERRAR VENTANA ACTIVA es decir el Login
                        new Tecnico().setVisible(true); //Abrimos ventana Técnico

                        //VENTANA DE CAPTURISTA
                    } else if (tipo_nivel.equals("Capturista") && estatus.equalsIgnoreCase("Activo")) {
                        dispose();  //CERRAR VENTANA ACTIVA es decir el Login
                        new Capturista().setVisible(true); //Abrimos ventana Capturista

                    }
                } else {
                    txt_user.setBackground(Color.red);
                    txt_password.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos.");
                    txt_user.setText("");
                    txt_password.setText("");
                    txt_user.setBackground(new Color(153, 153, 255));
                    txt_password.setBackground(new Color(153, 153, 255));

                }
            } catch (SQLException e) {
                System.err.println("Error en el boton Acceder " + e);
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión, contacte con el administrador.");
            }

        } else {
            txt_user.setBackground(Color.red);
            txt_password.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
            try {
                Thread.sleep(1000);
                txt_user.setBackground(new Color(153, 153, 255));
                txt_password.setBackground(new Color(153, 153, 255));
            } catch (Exception e) {
                System.out.println("Error en el hilo de pausa");
            }
        }
    }//GEN-LAST:event_btn_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acceder;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
